chat/urls.py
from django.urls import path
from .views import *

app_name = "chat"
urlpatterns = [
    path("chatpage", chat_view, name="index"),
]

chat_config/urls.py
# from django.urls import path
# from .consumers import *

# websocket_urlpatterns = [
#     path("ws/chatroom/<chatroom_name>", ChatroomConsumer.as_asgi()),
#     path("ws/online-status/", OnlineStatusConsumer.as_asgi()),
# ]

creator/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from .views import *

app_name = "creator"

urlpatterns = [
  path("", index, name="index"),
]

creatorhero/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("creator.urls")),
    path("user/", include("user.urls")),
    path("chat/", include("chat.urls"))
]

user/urls.py
from django.urls import path
from .views import *

app_name = "user"

urlpatterns = [
    path('login/', auth_login, name='login'),
    path('logout/', logout_view, name='logout'),
]

chat/models.py
from django.db import models
from django.contrib.auth.models import User
import shortuuid

class ChatGroup(models.Model):
    group_name = models.CharField(max_length=128, unique=True, default=shortuuid.uuid)
    groupchat_name = models.CharField(max_length=128, null=True, blank=True)
    admin = models.ForeignKey(User, related_name='groupchats', blank=True, null=True, on_delete=models.SET_NULL)
    users_online = models.ManyToManyField(User, related_name='online_in_groups', blank=True)
    members = models.ManyToManyField(User, related_name='chat_groups', blank=True)
    is_private = models.BooleanField(default=False)
    
    def __str__(self):
        return self.group_name
    
    
class GroupMessage(models.Model):
    group = models.ForeignKey(ChatGroup, related_name='chat_messages', on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.CharField(max_length=300)
    created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f'{self.author.username} : {self.body}'
    
    class Meta:
        ordering = ['-created']

chat_config/models.py
from django.db import models

# Create your models here.

user/models.py
from django.db import models

# Create your models here.

chat/forms.py
from django.forms import ModelForm
from django import forms
from .models import *

class ChatmessageCreateForm(ModelForm):
    class Meta:
        model = GroupMessage
        fields = ['body']
        widgets = {
            'body' : forms.TextInput(attrs={'placeholder': 'Add message ...', 'class': 'form-control', 'maxlength' : '300', 'autofocus': True }),
        }
        

user/forms.py
from django import forms
from django.contrib.auth import get_user_model

User = get_user_model()

class LoginForm(forms.Form):
    username = forms.CharField(label="Username")
    password = forms.CharField(widget=forms.PasswordInput, label="Password")

chat/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.http import Http404
from .models import *
from .forms import ChatmessageCreateForm
from django.contrib import messages
from django.shortcuts import redirect


def chat_view(request, chatroom_name='public-chat'):
    chat_group = get_object_or_404(ChatGroup, group_name=chatroom_name)
    chat_messages = chat_group.chat_messages.all()[:30]
    form = ChatmessageCreateForm()
    
    # other_user = None
    # if chat_group.is_private:
    #     if request.user not in chat_group.members.all():
    #         raise Http404()
    #     for member in chat_group.members.all():
    #         if member != request.user:
    #             other_user = member
    #             break
            
    # if chat_group.groupchat_name:
    #     if request.user not in chat_group.members.all():
    #         print("curr_user: ", request.user)
            # if request.user.emailaddress_set.filter(verified=True).exists():
            #     chat_group.members.add(request.user)
            # else:
            #     messages.warning(request, 'You need to verify your email to join the chat!')
            #     return redirect('profile-settings')
    
    print("test")
    print("request methood: ", request.method)
    print("request.POST: ", request.POST)
    if request.method == "POST":
        form = ChatmessageCreateForm(request.POST)
        if form.is_valid:
            message = form.save(commit=False)
            message.author = request.user
            message.group = chat_group
            message.save()
            # context = {
            #     'message' : message,
            #     'user' : request.user or None
            # }
            # return render(request, 'partial/chat_message_p.html', context)

        
    context = {
        'chat_messages' : chat_messages, 
        'form' : form,
        # 'other_user' : other_user,
        'chatroom_name' : chatroom_name,
        'chat_group' : chat_group
    }
    
    return render(request, "chat.html", context)

chat_config/views.py
from django.shortcuts import render

# Create your views here.

creator/views.py
from django.shortcuts import render
from .service import *

def index(request):
    csv_data = get_csv_data("creator_info.csv")
    labels = get_four_previous_weeks_date()
    chart_label = "Weekly subscribers"
    chart_data = get_subs_for_last_four_weeks()
    strength, weakness, to_do = get_analytics_restls()
    context = {
        "name": csv_data["Name"][0],
        "username": csv_data["username"][0],
        "total_likes": csv_data["Total likes"][0],
        "total_share": csv_data["Total share"][0],
        "total_comments": csv_data["Total comments"][0],
        "labels": labels,
        "chart_label": chart_label,
        "chart_data": chart_data,
        "strength": strength,
        "weakness": weakness,
        "to_do": to_do
    }
    return render(request, "index.html", context)

user/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from .forms import LoginForm

def auth_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('/') 
            else:
                form.add_error(None, 'Invalid username or password')
    else:
        form = LoginForm()
    return render(request, 'auth/login.html', {'form': form})

def logout_view(request):
    logout(request)
    return redirect('user:login')

templates/chat.html
{% extends 'partial/base.html' %}

{% block title %}
    Chat
{% endblock title %}

{% block content %}
<div class="row">
    <div class="col-3 border-end border-1 border-black me-5">
        <h3>Suggestion</h3>
        <div class="row my-3">
            <div class="col-3">
                <div style="width=70px; height: 70px;">
                    <img style="width=100%; height: 100%" src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-chat/ava2-bg.webp" alt="">
                </div>
            </div>
            <div class="col-9">
                <h5>Abraham</h5>
                <p>@abraham</p>
            </div>
        </div>
    </div>
    <div class="col-8">
        <div class="card" id="chat1" style="border-radius: 15px;">
            <div
                class="card-header d-flex justify-content-between align-items-center p-3 bg-info text-white border-bottom-0"
                style="border-top-left-radius: 15px; border-top-right-radius: 15px;">
                <i class="fas fa-angle-left"></i>
                <p class="mb-0 fw-bold">Abraham</p>
                <i class="fas fa-times"></i>
            </div>
            <div class="card-body" id="chat_container">
                <ul id="chat_messages">
                    {% for message in chat_messages reversed %}
                    {% include 'partial/chat_messages.html' %}
                    {% endfor %}
                    <div class="sticky bottom-0 z-10 p-2 bg-gray-800">
                        <div class="form-outline flex items-center rounded-xl px-2 py-2">
                            <form id="chat_message_form" class="w-full" method="POST">
                                {% for field in form %}
                                {% csrf_token %}
                                {{ field }}
                                {% endfor %}
                            </form>
                        </div>
                    </div>
                </ul>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

{% block script %}
<script>
    const scrollToBottom = () => {
        const container = document.getElementById('chat_container');
        container.scrollTop = container.scrollHeight;
    }
    scrollToBottom();
  </script> 
{% endblock script %}

templates/index.html
{% extends "partial/base.html" %}
{% load static %}

{% block title %}
    Dashboard
{% endblock title %}
{% block content %}
<div class="row">
  <div class="col-2">
    <div class="rounded-circle">
      <img
        src="{% static 'img/profile.jpg' %}"
        alt=""
        class="d-block"
        id="img-profile"
      />
    </div>
  </div>
  <div class="col-9 ms-4">
    <h3>Welcome Back</h3>
    <h1>{{ name }}</h1>
    <p>@johndoe</p>
  </div>
</div>
<div class="row my-5 border-bottom border-2 border-black">
  <div class="col-6">
    <button class="btn btn-outline-dark w-100" style="border: none">
      Followers
    </button>
  </div>
  <div class="col-6">
    <button class="btn btn-outline-dark w-100" style="border: none">
      Vidoes
    </button>
  </div>
</div>
<div class="row my-5">
  <div class="col-6">
    <canvas
      data-labels="{{ labels }}"
      data-chart_dat="{{ chart_data }}"
      id="chart"
    ></canvas>
  </div>
  <div class="col-6">
    <div class="row text-center">
      <div class="col-4">
        <div class="personal-info-icon borde w-100">
          <i class="bi bi-heart-fill"></i>
        </div>
        <p>{{ total_likes }}</p>
        <h6>Likes</h6>
      </div>
      <div class="col-4">
        <div class="personal-info-icon w-100">
          <i class="bi bi-share-fill"></i>
        </div>
        <p>{{ total_share }}</p>
        <h6>Shares</h6>
      </div>
      <div class="col-4">
        <div class="personal-info-icon w-100">
          <i class="bi bi-chat-left-fill"></i>
        </div>
        <p>{{ total_comments }}</p>
        <h6>Comments</h6>
      </div>
    </div>
  </div>
</div>
<div class="row my-5">
  <div class="my-2">
    <h3>Analytics Result</h3>
  </div>
  <div class="my-2">
    <div class="accordion" id="accordionPanelsStayOpenExample">
      <div class="accordion-item">
        <h2 class="accordion-header">
          <button
            id="strengthBtn"
            class="accordion-button"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#panelsStayOpen-collapseOne"
            aria-expanded="true"
            aria-controls="panelsStayOpen-collapseOne"
          >
            + Strength
          </button>
        </h2>
        <div
          id="panelsStayOpen-collapseOne"
          class="accordion-collapse collapse show"
        >
          <div class="accordion-body">
            <ul>
              {% for mystrenth in  strength %}
              <li class="my-2">
                {{ mystrenth }}
              </li>
              {% endfor %}
            </ul>
          </div>
        </div>
      </div>
      <div class="accordion-item">
        <h2 class="accordion-header">
          <button
            id="weaknessBtn"
            class="accordion-button collapsed"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#panelsStayOpen-collapseTwo"
            aria-expanded="true"
            aria-controls="panelsStayOpen-collapseTwo"
          >
            - Weakness
          </button>
        </h2>
        <div
          id="panelsStayOpen-collapseTwo"
          class="accordion-collapse collapse show"
        >
          <div class="accordion-body">
            <ul>
              {% for myweakness in  weakness %}
                  <li class="my-2">
                    {{ myweakness }}
                  </li>
                  {% endfor %}
            </ul>
          </div>
        </div>
      </div>
      <div class="accordion-item">
        <h2 class="accordion-header">
          <button
            id="todoBtn"
            class="accordion-button collapsed"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#panelsStayOpen-collapseThree"
            aria-expanded="true"
            aria-controls="panelsStayOpen-collapseThree"
          >
            ! To Do
          </button>
        </h2>
        <div
          id="panelsStayOpen-collapseThree"
          class="accordion-collapse collapse show"
        >
          <div class="accordion-body">
            <ul>
              {% for my_to_do in  to_do %}
                  <li class="my-2">
                    {{ my_to_do }}
                  </li>
                  {% endfor %}
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

{% block script %}  
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script> 
<script src="{% static 'js/index.js' %}"></script>
{% endblock script %}

templates/partial/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}Creator Hero{% endblock %}
    </title>
    {% comment %} bootstrap css link {% endcomment %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    {% comment %} bootstrap icon link {% endcomment %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    {% comment %} jquery link {% endcomment %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script> 
    {% comment %} hyperscript {% endcomment %}
    <script src="https://unpkg.com/hyperscript.org@0.9.12"></script>
    {% comment %} custom css {% endcomment %}
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    {% block style %} {% endblock style %}
</head>
<body>
    {% include 'partial/header.html' %}
    <main class="container-fluid px-4">
        <main class="row" style="min-height:100vh;">
           {% include 'partial/sidebar.html' %}
           <section class="col-9">
            {% comment %} custom content {% endcomment %}
              {% block content %} {% endblock content %}
        </section>
    </main>
    {% comment %} custom js {% endcomment %}
    {% block script %} {% endblock script %}
</body>
</html>

templates/partial/chat_message_p.html
{% include 'partial/chat_messages.html' %}

<script>
    scrollToBottom();
</script>

templates/partial/chat_messages.html
{% if message.author == user %}
<li class="d-flex flex-row justify-content-end mb-4">
    <div class="p-3 me-3 border" style="border-radius: 15px; background-color: #fbfbfb;">
        <p class="small mb-0">{{ message.body }}</p>
    </div>
    <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-chat/ava2-bg.webp"
        alt="avatar 1" style="width: 45px; height: 100%;">
</li>
{% else %}
<li class="d-flex flex-row justify-content-start mb-4">
    <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-chat/ava1-bg.webp"
        alt="avatar 1" style="width: 45px; height: 100%;">
    <div class="p-3 ms-3" style="border-radius: 15px; background-color: rgba(57, 192, 237,.2);">
        <p class="small mb-0">{{ message.body }}</p>
    </div>
</li>
{% endif %}

templates/partial/header.html
{% load static %}
<header class="shadow-sm p-3 mb-3 bg-body-tertiary rounded d-flex justify-content-between gap-4 align-items-center sticky-top">
    <section class="d-flex justify-content-start gap-4 align-items-center">
        <div>
            <img src="{% static 'img/creatorhero-logo.png' %}" alt="" style="width:75px; height:75px;">
        </div>
        <h3>Creatorhero</h3>
    </section>
    {% if user.is_authenticated %}
    <section class="d-flex justify-content-center gap-3">
        <a href="{% url 'user:logout' %}" class="btn btn-outline-dark">
            Logout
        </a>
    </section>
    {% else %}
    <section class="d-flex justify-content-center gap-3">
        <a href="{% url 'user:login' %}" class="btn btn-outline-dark">
            Login
        </a>
    </section>
    {% endif %}
</header>

templates/partial/sidebar.html
{% load static %}

{% block style %}
  <link rel="stylesheet" href="{% static 'css/sidebar.css' %}">
{% endblock style %}

{% load static %}
<section class="col-2 border-end border-1 border-black pe-3 me-5">
  <div class="my-3">
    <div class="d-flex gap-3">
        <i class="bi bi-house"></i>
        <a href="{% url 'creator:index' %}" class="custom-link-css">
        <h5>Dashboard</h5>
        </a>
      </div>
  </div>
  <div class="my-3">
    <div class="d-flex gap-3">
      <i class="bi bi-chat-square-dots"></i>
      <a href="{% url 'chat:index' %}" class="custom-link-css">
      <h5>Collaboraiton</h5>
      </a>
    </div>
  </div>
  <div class="my-3">
    <div class="d-flex gap-3">
      <i class="bi bi-lightbulb"></i>
      <h5>Sugested Topics</h5>
    </div>
  </div>
  <div class="my-3">
    <div class="d-flex gap-3">
      <i class="bi bi-person-plus-fill"></i>
      <h5>Sugested Creator</h5>
    </div>
  </div>
</section>